FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS build
WORKDIR /src

COPY LagoaSportRpa.csproj ./
RUN dotnet restore LagoaSportRpa.csproj

COPY . .
RUN dotnet publish LagoaSportRpa.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim AS runtime

ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENV ASPNETCORE_ENVIRONMENT=Production
ENV AGENDAMENTO__URLLOGIN=
ENV AGENDAMENTO__URLQUADRA=
ENV AGENDAMENTO__TEXTODIA=
ENV AGENDAMENTO__DURACAOHORAS=
ENV AGENDAMENTO__PARTICIPANTE__NOME=
ENV AGENDAMENTO__PARTICIPANTE__CPF=
ENV AGENDAMENTO__PARTICIPANTE__RG=
ENV AGENDAMENTO__PARTICIPANTE__TELEFONE=
ENV AGENDAMENTO__PARTICIPANTE__EMAIL=
ENV AGENDAMENTO__LOGINS__0__EMAIL=
ENV AGENDAMENTO__LOGINS__0__SENHA=
ENV AGENDAMENTO__LOGINS__0__HORARIO=
ENV AGENDAMENTO__LOGINS__1__EMAIL=
ENV AGENDAMENTO__LOGINS__1__SENHA=
ENV AGENDAMENTO__LOGINS__1__HORARIO=

WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "LagoaSportRpa.dll"]
